<template><view :data-skin="scenicSkin" class="visual-page ending safe"><EndingPoster v-if="ending" :id="id" :title="ending.title" :description="ending.description" :background="endingBackground" :luminous="id==='END06'"><template #actions><AssetButton disabled>观看完整结局</AssetButton><AssetButton :variant="id==='END06'?'light':'active'" @click="destiny">重建手记</AssetButton><AssetButton @click="newLoop">开始第 {{gameStore.state.playthrough+1}} 周目</AssetButton><AssetButton @click="home">首页</AssetButton></template><text class="section-label">第一卷 · 青崖山开门</text><text class="ending-meta">{{unlockedAt}}</text><view class="history"><text v-for="(h,i) in record?.choiceHistory" :key="i">{{h.text||h.choice}}</text></view><text class="ending-meta">{{record?.flags.route||'尚未记录'}} · 已解锁 {{gameStore.state.unlockedEndings.length}} / {{endingDefinitions.length}}</text><text class="ending-meta">本周目探索 {{Math.round((record?.visitedNodes.length||0)/38*100)}}%</text><text class="ending-meta">完整结局影片尚未提供</text></EndingPoster><view v-else class="ending-catalog visual-content"><text class="visual-title">第一卷的三种落款</text><view class="catalog-grid"><button role="button" tabindex="0" @keydown.enter.prevent="activateFocused" @keydown.space.prevent="activateFocused" v-for="e in endingDefinitions" :key="e.id" @click="openEnding(e.id)"><AssetPanel><text class="section-label">{{e.id}}</text><text class="catalog-title">{{gameStore.state.unlockedEndings.includes(e.id)?e.title:'尚未抵达'}}</text></AssetPanel></button></view><AssetButton @click="home">返回首页</AssetButton></view></view></template>
<script setup lang="ts">
import {activateFocused} from '../../utils/keyboard';

import AssetImage from '../../components/common/AssetImage.vue';import AssetPanel from '../../components/common/AssetPanel.vue';import AssetButton from '../../components/common/AssetButton.vue';import SceneBackdrop from '../../components/common/SceneBackdrop.vue';import {uiAssets} from '../../config/ui-assets';import {backgrounds} from '../../data/backgrounds';
import {computed,ref} from 'vue';import EndingPoster from '../../components/ending/EndingPoster.vue';import {gameStore,storyEngine} from '../../store/game';import {endingDefinitions} from '../../data/endings'
const selectedEnding=ref('');const id=computed(()=>selectedEnding.value||gameStore.state.currentEndingId),ending=computed(()=>endingDefinitions.find(e=>e.id===id.value)),unlockedAt=computed(()=>gameStore.state.endingUnlockedAt[id.value]?new Date(gameStore.state.endingUnlockedAt[id.value]).toLocaleString():'尚未解锁')
function destiny(){uni.redirectTo({url:'/pages/destiny/index'})}function newLoop(){storyEngine.startNewGame();uni.reLaunch({url:'/pages/play/index'})}function home(){uni.reLaunch({url:'/pages/home/index'})}
const endingBackground=computed(()=>backgrounds[('ending'+(id.value.slice(-2)||'01')) as keyof typeof backgrounds] || backgrounds.engagement)
const record=computed(()=>gameStore.state.currentEndingId===id.value?gameStore.state:[...gameStore.state.archives].reverse().find(a=>a.run.currentEndingId===id.value)?.run);
function openEnding(value:string){if(gameStore.state.unlockedEndings.includes(value))selectedEnding.value=value}
</script><style scoped>.ending-meta{display:block;font-size:11px;line-height:1.9;margin-top:16px;color:inherit;opacity:.65}.history{margin:20px 0}.history text{display:block;font:14px/1.9 'Songti SC',serif;margin-bottom:12px}.ending-catalog{padding:15vh 6vw;min-height:100vh}.catalog-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:20px;margin:40px 0}.catalog-grid button{background:none;color:#eee;margin:0;padding:0;text-align:left}.catalog-title{display:block;margin-top:20px;font:24px 'Songti SC',serif}@media(orientation:portrait){.catalog-grid{grid-template-columns:1fr 1fr}.catalog-title{font-size:20px}}</style>