<template><view :data-skin="scenicSkin" class="visual-page safe"><SceneBackdrop :src="backgrounds.paintedSkin" :shade=".78"/><TopBar title="图库" eyebrow="IMAGES FROM ANOTHER LIFE" @back="back" @settings="settings"/><view class="gallery-content visual-content"><view class="gallery-tabs"><AssetButton v-for="c in galleryCategories" :key="c" :variant="category===c?'active':'idle'" @click="category=c">{{c}}</AssetButton></view><view class="gallery-grid"><button role="button" tabindex="0" @keydown.enter.prevent="activateFocused" @keydown.space.prevent="activateFocused" v-for="item in filtered" :key="item.id" class="gallery-card" @click="selected=item"><AssetImage class="gallery-frame" :src="uiAssets.frames.photo" fit="fill"/><AssetImage class="gallery-art" :src="item.src"/><view class="gallery-caption"><text>{{item.title}}</text><text v-if="item.note&&gameStore.state.developerMode">{{item.note}}</text></view></button></view><text class="gallery-count">{{filtered.length}} 个画面</text></view><view v-if="selected" class="gallery-preview" @keydown="previewKeys" tabindex="-1"><view class="gallery-canvas" @touchstart="touchStart" @touchend="touchEnd"><AssetImage :src="selected.src" fit="contain" :style="{width:zoom*100+'%',height:zoom*100+'%'}"/></view><text>{{selected.title}}</text><text v-if="gameStore.state.developerMode" class="muted">{{selected.note}}</text><view class="viewer-actions"><AssetButton @click="step(-1)">上一张</AssetButton><AssetButton @click="zoom=zoom===1?2:1">{{zoom===1?'放大':'还原'}}</AssetButton><AssetButton @click="step(1)">下一张</AssetButton></view><AssetButton @click="selected=null"><AssetImage class="close-icon" :src="uiAssets.icons.close" fit="contain"/>关闭大图</AssetButton></view></view></template><script setup lang="ts">
import {activateFocused} from '../../utils/keyboard';

import {goBack} from '../../utils/navigation'
import {computed,ref,watch,nextTick} from 'vue';import {gameStore} from '../../store/game';import TopBar from '../../components/TopBar.vue';import AssetImage from '../../components/common/AssetImage.vue';import AssetButton from '../../components/common/AssetButton.vue';import SceneBackdrop from '../../components/common/SceneBackdrop.vue';import {uiAssets} from '../../config/ui-assets';import {backgrounds} from '../../data/backgrounds';import {gallery,galleryCategories,type GalleryItem} from '../../data/gallery';const category=ref('全部'),selected=ref<GalleryItem|null>(null),filtered=computed(()=>gallery.filter(i=>category.value==='全部'||i.categories.includes(category.value)));function back(){goBack()}function settings(){uni.navigateTo({url:'/pages/settings/index'})}const zoom=ref(1);let startX=0;watch(selected,()=>{zoom.value=1;nextTick(()=>{
// #ifdef H5
(document.querySelector('.gallery-preview') as HTMLElement|null)?.focus()
// #endif
})});function step(delta:number){const n=filtered.value.length;if(n)selected.value=filtered.value[(filtered.value.findIndex(x=>x.id===selected.value?.id)+delta+n)%n]}function previewKeys(e:KeyboardEvent){if(e.key==='Escape')selected.value=null;if(e.key==='ArrowLeft')step(-1);if(e.key==='ArrowRight')step(1)}function touchStart(e:TouchEvent){startX=e.touches[0].clientX}function touchEnd(e:TouchEvent){const dx=e.changedTouches[0].clientX-startX;if(zoom.value===1&&Math.abs(dx)>50)step(dx<0?1:-1)}
</script><style scoped>.gallery-content{padding:10px 4vw 45px}.gallery-tabs{display:flex;gap:10px;flex-wrap:wrap;margin-bottom:30px}.gallery-tabs .asset-button{min-width:88px;padding:12px 24px;font-size:12px}.gallery-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:22px}.gallery-card{position:relative;height:240px;background:none;padding:0;margin:0;border:0;border-radius:0;cursor:pointer;overflow:visible}.gallery-card:after{border:0}.gallery-frame{position:absolute;inset:0;z-index:2}.gallery-art{position:absolute;inset:14px;width:calc(100% - 28px);height:calc(100% - 28px)}.gallery-caption{position:absolute;z-index:3;left:20px;right:20px;bottom:20px;padding-top:35px;background:linear-gradient(0deg,#050506ee,transparent);text-align:left;color:#ebdfc7}.gallery-caption text{display:block;font-size:15px;line-height:1.6}.gallery-caption text:nth-child(2){font-size:10px;color:#bdb09c}.gallery-count{display:block;color:#c0ad8a;font-size:12px;margin-top:25px}.gallery-preview{position:fixed;inset:0;z-index:100;background:#050607f7;padding:35px;display:flex;flex-direction:column;align-items:center;gap:15px}.gallery-preview>.asset-image{height:75%;width:90%}.close-icon{display:inline-block;width:20px;height:20px;margin-right:8px;vertical-align:middle}@media(max-width:900px){.gallery-grid{grid-template-columns:repeat(2,1fr)}.gallery-card{height:220px}}.gallery-tabs .asset-button{border-width:0 0 1px;min-width:64px;padding:8px 15px;background:none}.gallery-tabs :deep(.asset-button__skin){opacity:.05}.gallery-card{height:32vh;min-height:210px;border:1px solid #b6915526;overflow:hidden}.gallery-frame{opacity:.13}.gallery-art{inset:0;width:100%;height:100%;transition:transform .4s}.gallery-card:hover .gallery-art{transform:scale(1.025)}.gallery-caption{left:14px;right:14px;bottom:12px}.gallery-preview{z-index:var(--z-modal);padding:max(18px,env(safe-area-inset-top)) 20px;gap:12px}.gallery-canvas{flex:1;width:100%;min-height:0;overflow:auto;display:block}.gallery-canvas .asset-image{width:100%;height:100%;transition:transform .25s;transform-origin:center}.viewer-actions{display:flex;gap:10px}.gallery-preview .asset-button{min-width:90px}.gallery-preview>.asset-button{min-height:40px}.gallery-grid{gap:18px}
@media(orientation:portrait){.gallery-grid{grid-template-columns:1fr 1fr;gap:12px}.gallery-card{height:25vh;min-height:170px}.gallery-tabs{gap:7px;margin-bottom:20px}.gallery-tabs .asset-button{font-size:12px;padding:8px 10px}.gallery-caption text{font-size:13px}.gallery-content{padding:10px 18px 30px}.viewer-actions .asset-button{min-width:80px}}
</style>
