<template><view :data-skin="scenicSkin" class="visual-page scenic-player"><SceneBackdrop :src="node.poster" :shade=".12"/><view class="scene-vignette"/><header class="story-header"><view><text class="eyebrow">青崖山开门 / EP. {{String(node.episode||35).padStart(2,'0')}}</text><text class="location">{{node.location||node.chapter}}</text></view><view class="nav"><button role="button" tabindex="0" @click="go('destiny')">重建手记</button><button role="button" tabindex="0" @click="go('evidence')">生态档案 {{s.evidenceIds.length}}</button><button role="button" tabindex="0" @click="home">{{townUnlocked(s)?'返回营地':'返回首页'}}</button></view></header><StoryPerformance v-if="beats.length" :node="node" :beats="beats" :index="lineIndex" :selecting="selecting" :choices="choices" @next="nextLine" @previous="previousLine" @choose="choose" @cancel="selecting=false"/><template v-else><view class="scene-caption"><text>{{node.chapter}}</text><text>地貌错位 · 生命越界 · 人间重建</text></view><view class="story-bottom"><view class="narrative"><text class="eyebrow">{{node.choices?.length?'现在，由你安排':'许知微 / 现场手记'}}</text><text class="story-title">{{node.title}}</text><text class="story-copy">{{node.description}}</text><text class="quote">“{{node.quote}}”</text><text v-if="outcome" class="outcome">上一步的回声 · {{outcome}}</text></view><view class="decision"><view class="resources"><text v-for="r in resources.slice(0,4)" :key="r.id">{{r.name}} <b>{{s.stats[r.id]}}</b></text></view><template v-if="node.choices?.length"><button role="button" tabindex="0" v-for="(c,i) in choices" :key="c.id" class="choice" :disabled="c.disabled" @click="choose(c.id)"><ScenicFrame kind="button" surface texture/><text class="letter">{{String.fromCharCode(65+i)}}</text><view><text>{{c.text}}</text><text class="hint">{{c.hint}}</text></view><text>›</text></button></template><AssetButton v-else @click="advance">继续故事　›</AssetButton><text class="save-note">图文剧情 · 本机自动保存 · {{episodeProgress(s)}}% 已抵达</text></view></view></template><view v-if="error" class="error">{{error}}</view></view></template>
<script setup lang="ts">
import StoryPerformance from '../../components/common/StoryPerformance.vue';import {storyBeats,beatIndex,moveBeat} from '../../data/story-performance';import {townUnlocked} from '../../data/town';import {computed,ref,watch} from 'vue';import {onShow} from '@dcloudio/uni-app';import SceneBackdrop from '../../components/common/SceneBackdrop.vue';import ScenicFrame from '../../components/common/ScenicFrame.vue';import AssetButton from '../../components/common/AssetButton.vue';import {gameStore,storyEngine} from '../../store/game';import {resources,latestOutcome,episodeProgress} from '../../data/scenic-progress';
const s=gameStore.state,node=computed(()=>storyEngine.getNode()),choices=computed(()=>storyEngine.getVisibleChoices()),outcome=computed(()=>latestOutcome(s)),error=ref('');
const beats=computed(()=>storyBeats(node.value)),lineIndex=computed(()=>beatIndex(s,node.value)),selecting=ref(false);
function nextLine(){if(moveBeat(s,node.value,1,gameStore.persist))return;if(node.value.choices?.length)selecting.value=true;else advance()}
function previousLine(){moveBeat(s,node.value,-1,gameStore.persist)}
function dispatch(){if(node.value.type==='ENDING')uni.redirectTo({url:'/pages/ending/index?id='+node.value.id})}watch(()=>s.currentNodeId,(id,old)=>{selecting.value=false;if(id==='EP13'&&old!=='EP13')uni.redirectTo({url:'/pages/town/index'});else dispatch()});onShow(dispatch);
function run(fn:()=>unknown){try{error.value='';fn()}catch(e){error.value=String(e)}}function advance(){run(()=>storyEngine.advance())}function choose(id:string){run(()=>storyEngine.applyChoice(id))}function go(page:string){uni.navigateTo({url:'/pages/'+page+'/index'})}function home(){uni.reLaunch({url:townUnlocked(s)?'/pages/town/index':'/pages/home/index'})}
</script>
<style scoped>
.scenic-player{min-height:100svh;color:#f7eddb;background:#142322;display:flex;flex-direction:column;padding:30px 4vw;box-sizing:border-box}.scene-vignette{position:absolute;inset:0;background:linear-gradient(0deg,#071513fa 0%,#071513d9 23%,#07151320 70%),linear-gradient(180deg,#071513a0,transparent 25%);pointer-events:none}.story-header{position:relative;display:flex;justify-content:space-between;gap:20px;align-items:center}.eyebrow{display:block;font:10px/1.7 sans-serif;letter-spacing:2px;color:#d5c39a}.location{display:block;font:16px/2 serif}.nav{display:flex;gap:16px}.nav button{background:#10231e66;border:1px solid #e7d5ae40;color:#f2e4c9;font-size:12px;padding:4px 12px;margin:0;min-height:44px}.scene-caption{position:relative;margin:12vh 0 auto;display:flex;flex-direction:column;gap:10px;text-shadow:0 2px 10px #000}.scene-caption>text:first-child{font:30px serif;letter-spacing:6px}.scene-caption>text:last-child{font-size:10px;letter-spacing:3px}.story-bottom{position:relative;display:grid;grid-template-columns:1.25fr 1fr;gap:6vw;padding-top:70px;align-items:end}.story-title{display:block;font:clamp(24px,3vw,42px)/1.4 serif;margin:10px 0 15px}.story-copy{display:block;white-space:pre-line;font:16px/1.9 serif;max-width:720px}.quote{display:block;color:#dec58f;font:italic 17px/1.8 serif;margin-top:16px}.outcome{display:block;border-left:2px solid #93b8a8;padding-left:12px;color:#acc7ba;font-size:11px;line-height:1.8;margin-top:14px}.resources{display:flex;justify-content:space-between;font-size:11px;color:#e3d6bb;border-bottom:1px solid #e2d0a738;padding-bottom:12px;margin-bottom:15px}.resources b{margin-left:8px;font:17px Georgia}.choice{position:relative;isolation:isolate;display:flex;align-items:center;gap:17px;width:100%;text-align:left;background:transparent;color:var(--text);margin:10px 0;padding:18px 26px;border:0;border-radius:0;font:16px/1.5 serif;--scenic-fill:var(--panel)}.choice:after{border:0}.choice>text,.choice>view:not(.scenic-frame){position:relative;z-index:2}.choice>view:not(.scenic-frame){flex:1}.letter{font:26px Georgia;color:var(--gold)}.hint{display:block;font:10px/1.7 sans-serif;color:var(--muted);margin-top:5px}.save-note{display:block;font-size:10px;color:#aaa995;text-align:right;margin-top:15px}.decision>.asset-button{width:100%}.error{position:relative;color:#ffd8ba}.choice:hover{filter:brightness(1.13)}
@media(max-height:600px) and (orientation:landscape){.scenic-player{padding:16px 3vw}.scene-caption{display:none}.story-bottom{padding-top:30px;gap:4vw}.story-copy{font-size:13px;line-height:1.65}.story-title{font-size:25px;margin:4px 0 8px}.quote{font-size:13px;margin-top:8px}.choice{padding:10px 22px;font-size:13px;margin:6px 0}.hint{font-size:9px}.outcome{font-size:10px}.resources{margin-bottom:6px}}
@media(orientation:portrait){.scenic-player{padding:22px}.nav{gap:6px}.nav button{font-size:10px;padding:4px 7px}.story-header{align-items:start}.location{font-size:12px}.eyebrow{font-size:8px}.scene-caption{margin-top:18vh}.story-bottom{grid-template-columns:1fr;gap:24px;padding-top:45px}.story-copy{font-size:15px}.story-title{font-size:30px}.choice{font-size:15px}.save-note{text-align:center}}
</style>
