<script setup>
import {ref,computed,onMounted,onBeforeUnmount} from 'vue'
import ColorPicker from './ColorPicker.vue'
const libraryOpen=ref(false),inspectorOpen=ref(false)
const project=ref(null),selected=ref(''),search=ref(''),chapter=ref(''),assets=ref([]),notice=ref('正在打开剧情工程…'),dirty=ref(false),busy=ref(false),report=ref(null),preview=ref(''),menu=ref(null),link=ref(null),zoom=ref(.7),offset=ref({x:50,y:60}),board=ref(null),upload=ref(null),replace=ref(null)
let token='',drag=null,history=[],future=[]
const clone=o=>JSON.parse(JSON.stringify(o))
const nodes=computed(()=>Object.values(project.value?.nodes||{})),current=computed(()=>project.value?.nodes[selected.value]),chapters=computed(()=>[...new Set(nodes.value.map(n=>n.chapter||'未分章'))]),visible=computed(()=>nodes.value.filter(n=>(!chapter.value||(n.chapter||'未分章')===chapter.value)&&(!search.value||`${n.id} ${n.title}`.includes(search.value))))
const ports=n=>n.choices?.length?n.choices.map((c,i)=>({key:c.id,text:c.text,target:c.next,index:i})):['ENDING','ROUTE_CLOSED'].includes(n.type)?[]:[{key:'next',text:'继续剧情',target:n.next,index:0}]
const edges=computed(()=>visible.value.flatMap(n=>ports(n).filter(p=>project.value.nodes[p.target]&&visible.value.some(v=>v.id===p.target)).map(p=>({source:n.id,...p}))))
const pos=id=>project.value.layout[id]||{x:0,y:0}
const start=e=>({x:pos(e.source).x+240,y:pos(e.source).y+168+e.index*32})
const end=id=>({x:pos(id).x,y:pos(id).y+76})
const curve=(a,b)=>`M${a.x},${a.y} C${a.x+100},${a.y} ${b.x-100},${b.y} ${b.x},${b.y}`
const path=e=>curve(start(e),end(e.target))
const nodeColor=n=>n.editorColor||(n.type==='ENDING'?'#cab87d':'#83cdb5')
const edgeColor=(source,key)=>project.value.nodes[source]?.editorEdgeColors?.[key]||'#83cdb5'
function setNodeColor(id,color){const n=project.value.nodes[id];if(!n||n.editorColor===color)return;checkpoint();if(color)n.editorColor=color;else delete n.editorColor;notice.value='节点边框颜色已修改，保存草稿后保留'}
function setEdgeColor(source,key,color){const n=project.value.nodes[source];if(!n||n.editorEdgeColors?.[key]===color)return;checkpoint();n.editorEdgeColors||={};if(color)n.editorEdgeColors[key]=color;else delete n.editorEdgeColors[key];notice.value='连线颜色已修改，保存草稿后保留'}
function checkpoint(){history.push(clone(project.value));if(history.length>60)history.shift();future=[];dirty.value=true;report.value=null}
function undo(){if(!history.length)return;future.push(clone(project.value));project.value=history.pop();dirty.value=true;report.value=null}
function redo(){if(!future.length)return;history.push(clone(project.value));project.value=future.pop();dirty.value=true;report.value=null}
async function api(route,data){const r=await fetch('/api/'+route,{method:data?'POST':'GET',headers:{'x-studio-token':token,...(data?{'Content-Type':'application/json'}:{})},body:data?JSON.stringify(data):undefined});const result=await r.json();if(!r.ok)throw Error(result.error);return result}
async function action(route){if(busy.value)return;busy.value=true;try{const snapshot=clone(project.value);if(route==='publish'){await api('save',snapshot);dirty.value=JSON.stringify(snapshot)!==JSON.stringify(project.value)}const r=await api(route,snapshot);if(route==='save'){dirty.value=JSON.stringify(snapshot)!==JSON.stringify(project.value);notice.value='草稿已保存，玩家剧情尚未改变'}else{report.value=r;inspectorOpen.value=true;notice.value=r.errors.length?'存在剧情中断，请先修复':route==='publish'?'已发布运行数据；重新构建游戏后生效':'剧情连通性检查通过'}}catch(e){notice.value=e.message}finally{busy.value=false}}
function layout(record=true){if(record)checkpoint();const depth={},queue=[['V_M01',0]];while(queue.length){const [id,d]=queue.shift();if(depth[id]!==undefined||!project.value.nodes[id])continue;depth[id]=d;ports(project.value.nodes[id]).forEach(p=>{if(p.target)queue.push([p.target,d+1])})}const rows={};nodes.value.forEach(n=>{const d=depth[n.id]??0,r=rows[d]||0;project.value.layout[n.id]={x:d*360,y:r*390};rows[d]=r+1})}
function point(e){const r=board.value.getBoundingClientRect();return {x:(e.clientX-r.left-offset.value.x)/zoom.value,y:(e.clientY-r.top-offset.value.y)/zoom.value}}
function beginNode(e,n){if(e.button!==0||e.target.closest('button'))return;e.preventDefault();checkpoint();selected.value=n.id;drag={type:'node',id:n.id,origin:point(e),pos:{...pos(n.id)}}}
function beginMiddlePan(e){if(e.button!==1)return;e.preventDefault();e.stopPropagation();link.value=null;beginPan(e)}
function beginPan(e){if(e.button!==1&&(e.button!==0||e.target.closest('.node,button,.edge')))return;e.preventDefault();menu.value=null;drag={type:'pan',x:e.clientX,y:e.clientY,pos:{...offset.value}}}
function move(e){if(link.value)link.value.point=point(e);if(!drag)return;if(drag.type==='node'){const p=point(e);project.value.layout[drag.id]={x:drag.pos.x+p.x-drag.origin.x,y:drag.pos.y+p.y-drag.origin.y}}else offset.value={x:drag.pos.x+e.clientX-drag.x,y:drag.pos.y+e.clientY-drag.y}}
function release(e){drag=null;if(link.value){const node=document.elementFromPoint(e.clientX,e.clientY)?.closest('[data-node]');if(node)connect(node.dataset.node);else link.value=null}}
function beginLink(e,source,key){e.stopPropagation();link.value={source,key,point:point(e)}}
function connect(target){if(!link.value)return;checkpoint();const {source,key}=link.value,n=project.value.nodes[source];if(key==='next')n.next=target;else n.choices.find(c=>c.id===key).next=target;notice.value=`路线已修改：${source} → ${target}`;link.value=null}
function wheel(e){const p=point(e),r=board.value.getBoundingClientRect();zoom.value=Math.min(1.8,Math.max(.15,zoom.value*(e.deltaY>0?.9:1.1)));offset.value={x:e.clientX-r.left-p.x*zoom.value,y:e.clientY-r.top-p.y*zoom.value}}
function context(e,id='',edge=null){menu.value={x:Math.min(e.clientX,innerWidth-220),y:Math.max(8,Math.min(e.clientY,innerHeight-(id?470:edge?235:170))),point:point(e),id,edge};if(id)selected.value=id}
function add(type='VIDEO',position=menu.value?.point||{x:100,y:100}){checkpoint();const id=(type==='VIDEO'?'V_':'P_')+Date.now().toString(36).toUpperCase();project.value.nodes[id]={id,type,title:type==='VIDEO'?'新视频':'新互动页面',chapter:chapter.value||'未分章',...(type==='PAGE'?{page:'phone',description:'在这里填写互动内容'}:{})};project.value.layout[id]={...position};selected.value=id;menu.value=null;return id}
function field(key,value){checkpoint();current.value[key]=value}
function choice(){const n=current.value;if(!n)return;const text=prompt('选项文字','新的选择');if(!text)return;checkpoint();const old=n.next;delete n.next;n.choices||=[];n.choices.push({id:'C_'+Date.now().toString(36),text,next:old||''});menu.value=null}
function remove(){const n=current.value;if(!n)return;if(n.id==='V_M01'){notice.value='游戏入口不可删除，可替换视频或修改后续';return}const incoming=nodes.value.flatMap(v=>ports(v).filter(p=>p.target===n.id));if(!confirm(`将「${n.title}」移到回收站？有 ${incoming.length} 条入线、${ports(n).filter(p=>p.target).length} 条出线。入线将断开，可撤销恢复；断线修复前禁止发布。`))return;checkpoint();project.value.trash.push(clone(n));for(const v of nodes.value){if(v.next===n.id)delete v.next;for(const c of v.choices||[])if(c.next===n.id)c.next=''}delete project.value.nodes[n.id];delete project.value.layout[n.id];selected.value='';menu.value=null}
function disconnect(edge){checkpoint();const n=project.value.nodes[edge.source];if(edge.key==='next')delete n.next;else n.choices.find(c=>c.id===edge.key).next='';menu.value=null}
function targetPrompt(edge){const target=prompt('输入目标节点 ID',edge.target||'');if(target===null)return;if(!project.value.nodes[target]){notice.value='目标不存在';return}link.value={source:edge.source,key:edge.key};connect(target);menu.value=null}
function assetNode(a,p){const id=add('VIDEO',p);project.value.nodes[id].title=a.name;project.value.nodes[id].video=a.url}
async function sendFile(file){const r=await fetch('/api/upload?name='+encodeURIComponent(file.name),{method:'POST',headers:{'x-studio-token':token},body:file});const data=await r.json();if(!r.ok)throw Error(data.error);return data.url}
async function thumbnail(file){return new Promise(resolve=>{const video=document.createElement('video'),url=URL.createObjectURL(file);let done=false;const finish=value=>{if(done)return;done=true;clearTimeout(timer);URL.revokeObjectURL(url);video.removeAttribute('src');video.load();resolve(value)};const timer=setTimeout(()=>finish(null),12000);video.muted=true;video.preload='auto';video.onloadedmetadata=()=>{video.currentTime=Math.min(1,video.duration/2)||0};video.onseeked=()=>{try{const canvas=document.createElement('canvas');canvas.width=480;canvas.height=Math.round(480*video.videoHeight/video.videoWidth);canvas.getContext('2d').drawImage(video,0,0,canvas.width,canvas.height);canvas.toBlob(blob=>finish(blob),'image/jpeg',.8)}catch{finish(null)}};video.onerror=()=>finish(null);video.src=url})}
async function files(list,p){const target=replace.value;replace.value=null;busy.value=true;try{let i=0;for(const file of list){if(!/\.(mp4|webm|mov)$/i.test(file.name))throw Error('请上传 MP4、WebM 或 MOV 视频');notice.value=`正在上传 ${file.name}…`;const url=await sendFile(file),thumb=await thumbnail(file);let poster;if(thumb)poster=await sendFile(new File([thumb],'cover.jpg'));const id=target&&project.value.nodes[target]?target:add('VIDEO',p?{x:p.x+i*280,y:p.y}:undefined);checkpoint();Object.assign(project.value.nodes[id],{video:url,title:file.name.replace(/\.[^.]+$/,''),poster});i++;if(target)break}assets.value=await api('assets');notice.value='上传完成，缩略图已生成；请连接路线并保存草稿'}catch(e){notice.value=e.message}finally{busy.value=false}}
function drop(e){if(e.dataTransfer.files.length)files(e.dataTransfer.files,point(e));else{try{assetNode(JSON.parse(e.dataTransfer.getData('application/story-asset')),point(e))}catch{}}}
function chooseFile(id=null){replace.value=id;upload.value.value='';upload.value.click();menu.value=null}
function key(e){if(['INPUT','TEXTAREA','SELECT'].includes(document.activeElement?.tagName))return;if(e.key==='Escape'){link.value=null;menu.value=null;preview.value=''}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();e.shiftKey?redo():undo()}}
function unload(e){if(dirty.value){e.preventDefault();e.returnValue=''}}
onMounted(async()=>{window.addEventListener('pointermove',move);window.addEventListener('pointerup',release);window.addEventListener('keydown',key);window.addEventListener('beforeunload',unload);try{const data=await api('project');token=data.token;project.value=data.project;if(!Object.keys(project.value.layout).length)layout(false);assets.value=await api('assets');notice.value='拖动卡片排版 · 从右侧圆点拖线到目标卡片 · 右键编辑'}catch(e){notice.value=e.message}})
onBeforeUnmount(()=>{window.removeEventListener('pointermove',move);window.removeEventListener('pointerup',release);window.removeEventListener('keydown',key);window.removeEventListener('beforeunload',unload)})
</script>
<template>
<div class="studio" @click="menu=null">
<header><div class="brand"><b>◈ STORY STUDIO</b><small>导演工作台 <em>仅本机 · 不进入玩家端</em></small></div><button class="panel-toggle" @click="libraryOpen=!libraryOpen;inspectorOpen=false">素材</button><button class="panel-toggle" @click="inspectorOpen=!inspectorOpen;libraryOpen=false">属性</button><span class="status">{{dirty?'● 未保存修改':'草稿工程'}}</span><button @click="undo">撤销</button><button @click="redo">重做</button><button @click="layout()">自动整理</button><button :disabled="busy" @click="action('check')">检查剧情</button><button :disabled="busy" @click="action('save')">保存草稿</button><button class="primary" :disabled="busy" @click="action('publish')">发布到游戏</button></header>
<div class="workspace" v-if="project">
<aside class="library" :class="{open:libraryOpen}"><div class="eyebrow">STORY MAP / 故事地图</div><h2>每个选择，都有去向。</h2><input v-model="search" placeholder="搜索剧情标题或 ID"><select v-model="chapter"><option value="">全部章节</option><option v-for="c in chapters">{{c}}</option></select><div class="counts"><b>{{nodes.length}}</b> 个节点 <b>{{edges.length}}</b> 条可见连线</div><h3>素材库 <button @click="chooseFile()">＋ 上传</button></h3><p class="hint">把视频拖到画布，自动创建节点。也可以直接拖入电脑里的视频。</p><div class="assets"><div v-for="a in assets" :key="a.url" class="asset" draggable="true" @dragstart="$event.dataTransfer.setData('application/story-asset',JSON.stringify(a))"><span>▷</span><div>{{a.name}}<small>{{nodes.some(n=>n.video===a.url)?'已使用':'未使用'}}</small></div></div><p v-if="!assets.length" class="hint">尚无本地视频素材</p></div><div class="hint">回收站 {{project.trash.length}} 个节点<br>误删后可使用 ⌘ / Ctrl + Z 撤销。<button v-if="project.trash.length" @click="checkpoint(); const n=project.trash.pop(); project.nodes[n.id]=n; project.layout[n.id]={x:100,y:100}">恢复最近删除节点</button></div></aside>
<main ref="board" class="board" @pointerdown.capture="beginMiddlePan" @pointerdown="beginPan" @auxclick.middle.prevent @wheel.prevent="wheel" @contextmenu.prevent="context($event)" @dragover.prevent @drop.prevent="drop">
<div class="canvas" :style="{transform:`translate(${offset.x}px,${offset.y}px) scale(${zoom})`}">
<svg class="wires"><defs><marker v-for="(e,i) in edges" :key="e.source+e.key" :id="'arrow-'+i" viewBox="0 0 10 10" refX="10" refY="5" markerWidth="8" markerHeight="8" orient="auto-start-reverse"><path d="M 0 0 L 10 5 L 0 10 z" :fill="edgeColor(e.source,e.key)"/></marker></defs><g v-for="(e,i) in edges" :key="e.source+e.key" class="edge" :style="{'--edge-color':edgeColor(e.source,e.key)}" @contextmenu.stop.prevent="context($event,'',e)"><path :d="path(e)" class="hit"/><path :d="path(e)" class="wire" :marker-end="`url(#arrow-${i})`"/><circle :cx="end(e.target).x-10" :cy="end(e.target).y" r="8" @pointerdown.stop="beginLink($event,e.source,e.key)"/></g><path v-if="link" :style="{'--edge-color':edgeColor(link.source,link.key)}" :d="curve(start({source:link.source,index:ports(project.nodes[link.source]).findIndex(p=>p.key===link.key)}),link.point)" class="wire draft"/></svg>
<article v-for="n in visible" :key="n.id" :data-node="n.id" class="node" :class="{selected:selected===n.id,ending:n.type==='ENDING'}" :style="{left:pos(n.id).x+'px',top:pos(n.id).y+'px','--node-color':nodeColor(n)}" @pointerdown.stop="beginNode($event,n)" @contextmenu.stop.prevent="context($event,n.id)">
<div class="cover"><img v-if="n.poster" draggable="false" :src="n.poster" @error="$event.target.style.display='none'"><span class="kind">{{n.type==='VIDEO'?'视频':n.type==='ENDING'?'结局':n.type==='ROUTE_CLOSED'?'路线结束':'互动选择'}}</span><button v-if="n.video" class="play" @click="preview=n.video">▷</button><span v-if="!n.poster" class="placeholder">{{n.type==='VIDEO'?'▷':'◇'}}</span></div><div class="node-title"><b>{{n.title||n.id}}</b><small>{{n.id}}</small></div><div v-for="p in ports(n)" :key="p.key" class="port"><span>{{p.text}}</span><button :style="p.target?{color:edgeColor(n.id,p.key)}:{}" :title="'拖到目标节点：'+(p.target||'尚未连接')" :class="{unlinked:!p.target}" @pointerdown.stop="beginLink($event,n.id,p.key)">●</button></div><div v-if="ports(n).some(p=>!p.target)" class="warning">⚠ 存在未连接的路线</div>
</article></div><div class="canvas-tools"><button @click="offset={x:50,y:60};zoom=.7">回到入口</button><span>{{Math.round(zoom*100)}}%</span><button @click="add()">＋ 视频</button><button @click="add('PAGE')">＋ 互动页</button></div></main>
<aside class="inspector" :class="{open:inspectorOpen}"><button class="panel-toggle" @click="inspectorOpen=false">收起 ×</button><div class="eyebrow">INSPECTOR / 节点属性</div><template v-if="current"><h2>{{current.title}}</h2><small>{{current.id}}</small><ColorPicker label="节点边框颜色" :model-value="nodeColor(current)" @change="setNodeColor(current.id,$event)"/><label>标题<input :value="current.title" @change="field('title',$event.target.value)"></label><label>章节<input :value="current.chapter" @change="field('chapter',$event.target.value)"></label><label v-if="current.type==='PAGE'">互动页面<select :value="current.page||''" @change="field('page',$event.target.value)"><option value="">通用文字页面</option><option value="phone">手机</option><option value="evidence">证据</option><option value="destiny">命运</option><option value="character">人物</option></select></label><label>页面内容<textarea :value="current.description" @change="field('description',$event.target.value)"/></label><label>制作备注（不会发布）<textarea :value="current.notes" @change="field('notes',$event.target.value)"/></label><button @click="chooseFile(current.id)">上传 / 替换视频</button><h3>跳转关系</h3><div v-for="p in ports(current)" :key="p.key" class="route"><input v-if="p.key!=='next'" :value="p.text" @change="checkpoint();current.choices.find(c=>c.id===p.key).text=$event.target.value"><span v-else>播放结束后</span><select :value="p.target||''" @change="link={source:current.id,key:p.key};connect($event.target.value)"><option value="">未连接</option><option v-for="n in nodes" :value="n.id">{{n.id}} · {{n.title}}</option></select><ColorPicker label="连线颜色" :model-value="edgeColor(current.id,p.key)" @change="setEdgeColor(current.id,p.key,$event)"/><button v-if="p.key!=='next'" @click="checkpoint();current.choices=current.choices.filter(c=>c.id!==p.key)">删除此选项</button></div><button v-if="!['ENDING','ROUTE_CLOSED'].includes(current.type)" @click="choice">＋ 增加选择</button></template><p v-else class="hint">选择一张卡片编辑内容。<br><br>拖动右侧圆点创建连线；拖动箭头端点修改目标。<br><br>右键卡片或连线显示操作菜单。</p><section v-if="report" class="report"><h3>剧情检查</h3><b>{{report.errors.length}} 错误 · {{report.warnings.length}} 提醒</b><p v-for="r in report.errors" class="error">{{r}}</p><p v-for="r in report.warnings">{{r}}</p></section></aside>
</div><footer>{{notice}}</footer>
<div v-if="menu" class="menu" :style="{left:menu.x+'px',top:menu.y+'px'}" @click.stop><template v-if="menu.edge"><ColorPicker label="连线颜色" :model-value="edgeColor(menu.edge.source,menu.edge.key)" @change="setEdgeColor(menu.edge.source,menu.edge.key,$event)"/><button @click="targetPrompt(menu.edge)">修改连线目标</button><button @click="disconnect(menu.edge)">断开连线</button></template><template v-else-if="menu.id"><ColorPicker label="节点边框颜色" :model-value="nodeColor(project.nodes[menu.id])" @change="setNodeColor(menu.id,$event)"/><button :disabled="!current?.video" @click="preview=current.video;menu=null">预览视频</button><button @click="chooseFile(menu.id)">上传 / 替换视频</button><button v-if="!['ENDING','ROUTE_CLOSED'].includes(current?.type)" @click="choice">增加选择</button><button @click="add('VIDEO',{x:pos(menu.id).x+360,y:pos(menu.id).y})">在旁边增加视频</button><button @click="add('PAGE',{x:pos(menu.id).x+360,y:pos(menu.id).y+300})">增加互动页面</button><button class="danger" @click="remove">移到回收站</button></template><template v-else><button @click="add()">新增视频节点</button><button @click="add('PAGE')">新增互动页面</button><button @click="chooseFile()">上传视频</button></template></div>
<div v-if="preview" class="modal" @click.self="preview=''"><button @click="preview=''">关闭预览 ×</button><video :src="preview" controls autoplay @error="notice='视频无法播放，请检查素材文件或浏览器格式支持'"/></div><input ref="upload" type="file" accept=".mp4,.webm,.mov" multiple hidden @change="files($event.target.files)">
</div>
</template>
