<template><view :data-skin="scenicSkin" class="visual-page closed safe"><SceneBackdrop :src="backgrounds.hospital7" :shade=".35" fractured/><AssetImage class="closed-flame" :src="uiAssets.destiny.fire" fit="contain"/><AssetPanel class="closed-panel"><text class="section-label">A PATH HAS ENDED</text><text class="closed-title">ROUTE CLOSED</text><AssetImage class="visual-divider" :src="uiAssets.decorations.divider" fit="contain"/><text class="closed-quote">{{node.title}}</text><text class="visual-copy">{{node.description}}</text><text v-if="showReason" class="reason">{{node.reason}}</text><view class="asset-actions"><AssetButton @click="retry">回到选择</AssetButton><AssetButton @click="chapter">回到本章</AssetButton><AssetButton variant="active" @click="evidence">查看遗漏</AssetButton></view></AssetPanel><AssetImage class="broken-line" :src="uiAssets.decorations.crack" fit="fill"/></view></template>
<script setup lang="ts">
import AssetImage from '../../components/common/AssetImage.vue';import AssetPanel from '../../components/common/AssetPanel.vue';import AssetButton from '../../components/common/AssetButton.vue';import SceneBackdrop from '../../components/common/SceneBackdrop.vue';import {uiAssets} from '../../config/ui-assets';import {backgrounds} from '../../data/backgrounds';
import {computed,ref} from 'vue';import {storyEngine} from '../../store/game'
const node=computed(()=>storyEngine.getNode()),showReason=ref(false)
function restore(chapter=false){if(storyEngine.restoreCheckpoint(chapter))uni.reLaunch({url:'/pages/play/index'});else uni.showToast({title:'旧存档没有回退快照，请从首页开始新人生',icon:'none'})}
function retry(){restore()}function chapter(){restore(true)}function evidence(){showReason.value=!showReason.value}
</script><style scoped>.closed{display:flex;align-items:center;justify-content:center;padding:70px 5vw;min-height:100vh}.closed-panel{width:min(850px,90vw);text-align:center}.closed-panel :deep(.asset-panel__body){padding:65px 40px}.closed-title{display:block;font-family:serif;font-size:clamp(28px,5vw,62px);letter-spacing:.2em;margin:18px 0}.closed-quote{display:block;font-size:23px;margin:15px 0}.closed-panel .visual-divider{margin:20px auto}.asset-actions{justify-content:center;margin-top:35px}.reason{display:block;color:#d7c5a5;font-size:13px;line-height:1.8;margin-top:20px}.closed-flame{position:absolute;top:5%;right:5%;width:90px;height:90px;opacity:.6}.broken-line{position:absolute;left:10%;bottom:5%;width:80%;height:35px;mix-blend-mode:screen;opacity:.5}@media(max-width:600px){.closed-panel :deep(.asset-panel__body){padding:35px 20px}.closed-title{font-size:28px;letter-spacing:.1em}}.closed{align-items:flex-end;justify-content:flex-start;padding:12vh 5vw 9vh}.closed-panel{width:min(650px,62vw);text-align:left;background:none;--panel-opacity:.09}.closed-panel :deep(.asset-panel__body){padding:30px 0}.closed-title{font-size:clamp(28px,4vw,60px);letter-spacing:.14em}.closed-panel .visual-divider{margin:18px 0;width:200px;opacity:.55}.closed-panel .asset-actions{justify-content:flex-start;gap:12px}.closed-flame{opacity:.12;width:50px}.broken-line{opacity:.12;width:35%;left:4%;height:15vh;bottom:0}.closed-quote{font-family:'Songti SC',serif}.closed :deep(.scene-backdrop__crack){opacity:.08}
@media(orientation:portrait){.closed{padding:45vh 6vw 6vh}.closed-panel{width:100%}.closed-title{font-size:30px}.closed-panel .asset-actions{flex-wrap:wrap}.closed-panel :deep(.asset-panel__body){padding:0}}
</style>
