<template><view :data-skin="scenicSkin" class="visual-page safe"><SceneBackdrop :src="backgrounds.paintedSkin" :shade=".65"/><TopBar title="章节" eyebrow="CHAPTERS OF A LIFE" @back="back" @settings="settings"/><view class="chapters-content visual-content"><view class="chapter-heading"><AssetImage :src="uiAssets.destiny.fan" fit="contain"/><text>每一段旅程，都是重建的开始</text></view><view class="skin-unlock-note"><SkinSwitch/><text>{{skinStore.unlocked.value?'序章已通关 · 余烬鎏金可自由切换':'通关序章，开启余烬鎏金深色篇章'}}</text></view><view class="chapters-grid"><button role="button" tabindex="0" @keydown.enter.prevent="activateFocused" @keydown.space.prevent="activateFocused" v-for="c in chapters" :key="c.id" class="chapter-card" :class="{unseen:!exploration(c.id).seen}" @click="selected=c"><ScenicFrame class="chapter-reference-frame" kind="chapter"/><view class="chapter-surface" :style="{clipPath:chapterClip}"><AssetImage class="chapter-art" :src="c.image"/><view class="chapter-caption"><text>第 {{c.order}} 幕</text><text>{{c.title}}</text><text class="chapter-status">{{exploration(c.id).total?exploration(c.id).percent+'% · '+(exploration(c.id).seen?'已阅':'尚未抵达'):'尚待展开'}}</text><AssetImage :src="uiAssets.decorations.line" fit="fill"/></view></view></button></view><AssetButton v-if="gameStore.state.hasSave" @click="play">返回当前剧情</AssetButton></view><view v-if="selected" class="chapter-preview"><AssetImage :src="selected.image" fit="contain"/><text>{{selected.title}} · 场景预览</text><AssetButton @click="selected=null">关闭预览</AssetButton></view></view></template><script setup lang="ts">
import ScenicFrame from '../../components/common/ScenicFrame.vue'
import {frameClipPath} from '../../config/scenic-frame-shapes'
import {scenicAssets} from '../../config/scenic-assets'
const chapterClip=computed(()=>{const dark=skinStore.active.value==='dark';const [, , w,h]=scenicAssets[dark?'darkPanel':'lightPanel'].box;return frameClipPath(dark?'dark-panel':'light-panel',{x:Math.round(w*.16)/w,y:Math.round(h*.20)/h,edgeX:20,edgeY:20})})
import SkinSwitch from '../../components/common/SkinSwitch.vue';import {skinStore} from '../../store/skin';
import {activateFocused} from '../../utils/keyboard';

import {goBack} from '../../utils/navigation'
import {computed,ref} from 'vue';import {story} from '../../data/story';import {storyVisuals} from '../../data/story-visuals';import TopBar from '../../components/TopBar.vue';import AssetImage from '../../components/common/AssetImage.vue';import AssetButton from '../../components/common/AssetButton.vue';import SceneBackdrop from '../../components/common/SceneBackdrop.vue';import {uiAssets} from '../../config/ui-assets';import {backgrounds} from '../../data/backgrounds';import {chapters,type ChapterMeta} from '../../data/chapters';import {gameStore} from '../../store/game';const selected=ref<ChapterMeta|null>(null);function back(){goBack()}function settings(){uni.navigateTo({url:'/pages/settings/index'})}function play(){uni.navigateTo({url:'/pages/play/index'})}function exploration(id:string){const ids=Object.keys(story).filter(n=>story[n].episode&&story[n].chapterId===id);const seen=ids.filter(n=>gameStore.state.visitedNodes.includes(n)).length;return {total:ids.length,seen,percent:ids.length?Math.round(seen/ids.length*100):0}}
</script><style scoped>.chapter-reference-frame{z-index:4;}.skin-unlock-note{display:flex;align-items:center;gap:20px;flex-wrap:wrap;margin:0 0 24px;font-size:12px;color:var(--muted)}.chapters-content{padding:20px 4vw 50px}.chapter-heading{display:flex;align-items:center;gap:15px;margin-bottom:25px;font-size:16px;color:#d1bc99}.chapter-heading .asset-image{width:55px;height:55px}.chapters-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:22px;margin-bottom:30px}.chapter-card{position:relative;height:340px;background:none;border:0;padding:0;margin:0;border-radius:0;cursor:pointer;overflow:visible}.chapter-card:after{border:0}.chapter-frame{position:absolute;inset:0;z-index:2}.chapter-art{position:absolute;inset:17px 16px;width:calc(100% - 32px);height:calc(100% - 34px)}.chapter-caption{position:absolute;left:22px;right:22px;bottom:27px;z-index:3;text-align:left;color:#f0e1c7;background:linear-gradient(0deg,#000c,transparent);padding-top:50px}.chapter-caption text{display:block;font-size:11px;margin-bottom:7px}.chapter-caption text:nth-child(2){font-size:24px;font-family:serif}.chapter-caption .asset-image{height:10px}.chapters-content>.asset-button{width:200px}.chapter-preview{position:fixed;inset:0;z-index:100;background:#050607f5;padding:40px;display:flex;flex-direction:column;align-items:center;gap:20px}.chapter-preview>.asset-image{height:80%}.chapter-preview>text{font-size:18px}@media(max-width:850px){.chapters-grid{grid-template-columns:repeat(2,1fr)}.chapter-card{height:290px}}.chapters-grid{display:flex;overflow-x:auto;gap:18px;padding:5px 0 18px;scroll-snap-type:x proximity}.chapter-card{flex:0 0 clamp(170px,18vw,290px);height:58vh;min-height:300px;max-height:580px;scroll-snap-align:start;overflow:hidden;border:1px solid #b6915533}.chapter-frame{opacity:.15;pointer-events:none}.chapter-art{inset:0;width:100%;height:100%;transition:filter .3s,transform .5s}.chapter-card:hover .chapter-art{transform:scale(1.025)}.unseen .chapter-art{filter:saturate(.25) brightness(.65)}.unseen:before{content:'';position:absolute;inset:0;background:linear-gradient(0deg,#bfc6c815,transparent 80%);z-index:1;pointer-events:none}.chapter-caption{left:16px;right:16px;bottom:15px;padding-top:100px}.chapter-caption .chapter-status{font:10px ui-monospace,monospace;opacity:.8}.chapter-caption .asset-image{height:3px;opacity:.5}.chapter-heading .asset-image{width:30px;height:30px;opacity:.5}.chapter-heading{font:16px 'Songti SC',serif}
@media(orientation:portrait){.chapters-grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}.chapter-card{height:38vh;min-height:240px}.chapter-caption text:nth-child(2){font-size:22px}}
@media(max-height:540px) and (orientation:landscape){.chapter-card{height:62vh;min-height:200px}.chapter-heading{margin-bottom:12px}}
.chapter-surface{position:absolute;inset:0;overflow:hidden}.chapter-card{overflow:visible;border:0!important}.unseen:before{display:none}
</style>
