export const art: Record<string, string> = {
  ...Object.fromEntries(['props','buildings','xuzhiwei','water'].map(key=>['town-'+key,'assets/town-'+key+'.png'])),
  hero: 'assets/qingya.jpg',
  ...Object.fromEntries(['exam','qingya','wetland','refugees','market','titan'].map(key=>[key,'assets/'+key+'.jpg'])),
  'light-title': 'assets/light-title.png',
  'dark-title': 'assets/dark-title.png',
  'light-button': 'assets/light-button.png',
  'dark-button': 'assets/dark-button.png',
  'light-panel': 'assets/light-panel.png',
  'dark-panel': 'assets/dark-panel.png',
  'icon-routes': 'assets/icon-routes.png',
  'icon-archive': 'assets/icon-archive.png',
  'icon-gallery': 'assets/icon-gallery.png',
  'icon-characters': 'assets/icon-characters.png',
  'gold-flare': 'assets/gold-flare.png',
  grain: 'assets/grain.png',
  seal: 'assets/seal.png',
}
