<template><view :data-skin="scenicSkin" class="visual-page safe"><SceneBackdrop :src="backgrounds.highDimension" :shade=".66"/><TopBar title="命运地图" eyebrow="EVERY CHOICE LEAVES A TRACE" @back="home" @settings="settings"/><view class="destiny-layout visual-content"><scroll-view scroll-x scroll-y class="map-scroll"><view class="network"><AssetImage class="center-compass" :src="uiAssets.destiny.compass" fit="contain"/><view class="center"><AssetImage class="center-ring" :src="uiAssets.destiny.ring" fit="contain"/><AssetImage class="center-portrait" :src="uiAssets.portraits.shenzhiyi"/><text>沈知意</text></view><DestinyEdge v-for="edge in edges" :key="edge.id" :from="edge.from" :to="edge.to" :broken="edge.broken" :type="edge.type"/><DestinyNode v-for="id in visited" :key="id" class="map-node" :style="{left:positions[id].x-37+'px',top:positions[id].y-32+'px'}" :label="story[id]?.title||id" :portrait="portraitFor(id)" :tooltip="tooltip(id)" :type="id==='END06'?'TRUE_ROUTE':story[id]?.type" :selected="selected===id" @select="selected=id"/><text v-if="!visited.length" class="empty-note">从首页开始新人生，命运将在这里留下轨迹。</text></view></scroll-view><AssetPanel class="map-detail"><view class="legend"><view v-for="[type,label] in legend" :key="type"><DestinyNode :type="type" :label="label"/></view></view><AssetImage class="visual-divider" :src="uiAssets.decorations.divider" fit="contain"/><text class="section-label">{{selected || '你的轨迹'}}</text><text class="detail-title">{{selected?story[selected]?.title:'已走节点 '+visited.length}}</text><view class="choice-history"><text v-for="(h,i) in selectedChoices" :key="i">{{h.text||h.choice}}</text><text v-if="selected&&!selectedChoices.length">该节点没有选择记录。</text></view><text class="unlocked">已解锁结局：{{s.unlockedEndings.join('、')||'暂无'}}</text><view class="map-actions"><AssetButton v-if="s.hasSave" @click="continueGame">返回当前进度</AssetButton><AssetButton variant="active" @click="newGame">开始第 {{s.playthrough+1}} 周目</AssetButton></view></AssetPanel></view></view></template>
<script setup lang="ts">
import AssetImage from '../../components/common/AssetImage.vue';import AssetPanel from '../../components/common/AssetPanel.vue';import AssetButton from '../../components/common/AssetButton.vue';import SceneBackdrop from '../../components/common/SceneBackdrop.vue';import DestinyNode from '../../components/destiny/DestinyNode.vue';import DestinyEdge from '../../components/destiny/DestinyEdge.vue';import {uiAssets} from '../../config/ui-assets';import {backgrounds} from '../../data/backgrounds';
import {computed,ref} from 'vue';import TopBar from '../../components/TopBar.vue';import {gameStore,storyEngine} from '../../store/game';import {story} from '../../data/story';import {storyVisuals} from '../../data/story-visuals';import {characters} from '../../data/characters'
const s=gameStore.state,selected=ref(''),visited=computed(()=>[...new Set([...s.archives.flatMap(a=>a.run.visitedNodes),...s.visitedNodes])]),selectedChoices=computed(()=>[...s.archives.flatMap(a=>a.run.choiceHistory),...s.choiceHistory].filter(h=>h.node===selected.value))
function color(id:string){return id==='END06'?'#e5c982':({VIDEO:'#5a8cff',PAGE:'#9a6bff',CHOICE:'#e49a4c',ROUTE_CLOSED:'#90949a',ENDING:'#64c987'}[story[id]?.type]||'#999')}
function home(){uni.reLaunch({url:'/pages/home/index'})}function continueGame(){storyEngine.continueGame();uni.reLaunch({url:'/pages/play/index'})}function newGame(){uni.showModal({title:'开始新人生',content:'当前周目将保留在存档中。',success:r=>{if(r.confirm){storyEngine.startNewGame();uni.reLaunch({url:'/pages/play/index'})}}})}
const positions=computed(()=>{
 const points=visited.value.map((id,i)=>{const angle=Object.keys(story).indexOf(id)*2.399963-Math.PI/2;const r=story[id]?.type==='ENDING'?325:story[id]?.choices?220:285;return {id,x:430+Math.cos(angle)*r,y:320+Math.sin(angle)*r*.82}})
 for(let pass=0;pass<65;pass++)for(let i=0;i<points.length;i++){const a=points[i];for(let j=i+1;j<points.length;j++){const b=points[j],dx=b.x-a.x,dy=b.y-a.y,d=Math.hypot(dx,dy)||1;if(d<98){const f=(98-d)*.25;a.x-=dx/d*f;a.y-=dy/d*f;b.x+=dx/d*f;b.y+=dy/d*f}}const dx=a.x-430,dy=a.y-320,d=Math.hypot(dx,dy)||1;if(d<158){a.x=430+dx/d*158;a.y=320+dy/d*158}a.x=Math.max(55,Math.min(810,a.x));a.y=Math.max(48,Math.min(600,a.y))}
 return Object.fromEntries(points.map(({id,x,y})=>[id,{x,y}]))
})
const edges=computed(()=>visited.value.flatMap(id=>{const next=story[id]?.next;const targets=[next,...[...s.archives.flatMap(a=>a.run.choiceHistory),...s.choiceHistory].filter(h=>h.node===id).map(h=>story[id]?.choices?.find(c=>c.id===h.choice)?.next)].filter((v):v is string=>!!v&&!!positions.value[v]);return [...new Set(targets)].map(to=>({id:id+'-'+to,from:positions.value[id],to:positions.value[to],broken:story[to]?.type==='ROUTE_CLOSED',type:to==='END06'?'TRUE_ROUTE':story[to]?.type==='ENDING'?'ENDING':story[id]?.choices?'CHOICE':story[to]?.type}))}))
const legend=[['VIDEO','剧情'],['PAGE','互动'],['CHOICE','选择'],['ROUTE_CLOSED','断路'],['ENDING','结局'],['TRUE_ROUTE','真结局']]
function settings(){uni.navigateTo({url:'/pages/settings/index'})}
function portraitFor(id:string){const cid=storyVisuals[id]?.characterId;return cid?characters.find(c=>c.id===cid)?.portrait:undefined}
function tooltip(id:string){const n=story[id];const h=[...s.archives.flatMap(a=>a.run.choiceHistory),...s.choiceHistory].filter(h=>h.node===id);return [n?.title||id,n?.chapter||'人生分支',...h.map(x=>x.text||x.choice),s.currentNodeId===id?'当前所在':'已抵达'].join(' · ')}
</script><style scoped>.destiny-layout{display:grid;grid-template-columns:minmax(0,1fr) 280px;gap:20px;padding:0 3vw 35px}.map-scroll{height:650px;width:100%;background:#03080b66}.network{position:relative;width:880px;height:650px}.center{position:absolute;left:360px;top:240px;width:140px;height:180px;z-index:3}.center-ring{position:absolute;width:140px;height:140px}.center-portrait{position:absolute;left:15px;top:15px;width:110px;height:110px;border-radius:50%}.center text{position:absolute;top:150px;text-align:center;width:100%;font-family:serif;letter-spacing:.2em}.center-compass{position:absolute;left:310px;top:195px;width:240px;height:240px;opacity:.25}.map-node{position:absolute;z-index:4}.legend{display:grid;grid-template-columns:repeat(3,1fr);gap:8px}.legend .destiny-node{transform:scale(.7);transform-origin:center;width:64px;height:65px}.detail-title{display:block;font-size:20px;margin:20px 0;line-height:1.5}.choice-history text{display:block;font-size:12px;color:#cabcaa;line-height:1.8;margin-bottom:10px}.map-actions{display:flex;flex-direction:column;gap:12px;margin-top:25px}.unlocked{font-size:11px;color:#cbb084}.map-detail .visual-divider{width:100%}.empty-note{position:absolute;left:200px;bottom:80px;color:#c4b295;font-size:14px}@media(max-width:900px){.destiny-layout{display:block}.map-scroll{height:540px}.map-detail{margin-top:20px}.legend{display:flex;justify-content:center}.map-actions{flex-direction:row;flex-wrap:wrap}}.destiny-layout{grid-template-columns:minmax(0,1fr) 250px;gap:15px}.map-scroll{background:radial-gradient(ellipse,#7fa9a312,transparent 70%);height:calc(100vh - 130px);min-height:540px}.network{background:radial-gradient(ellipse at 49% 48%,#d0bc8c0d,transparent 45%)}.center-compass{opacity:.1}.center-ring{opacity:.65}.map-detail{--panel-opacity:.18;background:linear-gradient(90deg,transparent,#08090b66)}.detail-title{font-family:'Songti SC',serif;font-size:22px}.legend{grid-template-columns:1fr 1fr}.legend .destiny-node{transform:none;width:70px;height:70px}.legend :deep(.node-skin){width:22px;height:22px;left:22px;top:0}.legend :deep(.node-label){top:28px;left:0;font-size:10px}.map-actions .asset-button{min-width:0;width:100%;font-size:12px}.map-node{transition:left .6s,top .6s}
@media(max-width:1000px){.destiny-layout{display:block}.map-scroll{height:66vh;min-height:420px}.map-detail{margin-top:15px}.legend{display:flex;justify-content:center}.map-actions{flex-direction:row}.map-actions .asset-button{width:auto}.map-detail :deep(.asset-panel__body){padding:18px}.network{min-width:880px}.map-detail .detail-title{margin:14px 0}}
@media(orientation:portrait){.destiny-layout{padding:0 12px 30px}.map-scroll{height:55vh;min-height:370px}.map-detail{background:#0b111577}.legend{justify-content:space-between}.legend .destiny-node{width:46px}.legend :deep(.node-skin){left:12px}}
.network{margin:clamp(0px,calc((100vh - 800px)/2),140px) auto 0}.map-detail{align-self:start;max-height:calc(100vh - 125px);overflow:auto}.map-scroll{background:radial-gradient(ellipse,#7fa9a315,transparent 70%)}@media(max-width:1000px){.network{margin:0 auto}.map-detail{max-height:none}} </style>
