<template><view class="choice-wrap" :class="{major}" @keydown="navigate"><AssetImage v-if="major" class="major-crack" :src="uiAssets.decorations.crack" fit="contain"/><AssetImage v-if="major" class="major-portrait" :src="uiAssets.hero.shenzhiyi" position="center top" fit="contain"/><view class="choice-box"><view class="head"><text class="title">{{title||'现在，你怎么选？'}}</text><view v-if="seconds>0" class="timer" role="timer" :aria-label="`剩余 ${seconds} 秒`"><AssetImage :src="uiAssets.icons.countdown" fit="contain"/><text>{{seconds}}</text></view></view><view class="options" :class="{hovering:hoverIndex>=0}" @mouseleave="hoverIndex=-1"><ChoiceItem v-for="(item,i) in choices" :key="item.id" :item="item" :major="major" :developer-mode="developerMode" :busy="locked" :selected="selected===item.id" :class="{'branch-dim':major&&hoverIndex>=0&&hoverIndex!==i}" @mouseenter="hoverIndex=i" @pick="pick"/></view><text v-if="major" class="major-note">每一条路，都是另一个我</text></view></view></template>
<script setup lang="ts">
import AssetImage from '../common/AssetImage.vue';import ChoiceItem from './ChoiceItem.vue';import {uiAssets} from '../../config/ui-assets';import {onMounted,onUnmounted,ref,nextTick} from 'vue';import type {ChoiceItem as Choice} from '../../data/story';const props=defineProps<{title?:string;choices:Choice[];countdown?:number;developerMode?:boolean;major?:boolean;paused?:boolean}>();const emit=defineEmits<{select:[string]}>();const selected=ref(''),locked=ref(false),seconds=ref(props.countdown||0),hoverIndex=ref(-1);let timer:ReturnType<typeof setInterval>;let commit:ReturnType<typeof setTimeout>;
function pick(item:Choice){if(locked.value||item.disabled)return;locked.value=true;selected.value=item.id;clearInterval(timer);commit=setTimeout(()=>emit('select',item.id),180)}
function navigate(event:KeyboardEvent){if(!['ArrowDown','ArrowUp'].includes(event.key))return;event.preventDefault();const root=typeof document!=='undefined'?document.querySelector('.choice-wrap'):null;if(!root)return;const buttons=Array.from(root.querySelectorAll<HTMLElement>('.choice-item[tabindex="0"]'));const index=buttons.indexOf(document.activeElement as HTMLElement);buttons[(index+(event.key==='ArrowDown'?1:-1)+buttons.length)%buttons.length]?.focus()}
onMounted(()=>{nextTick(()=>{
// #ifdef H5
(document.querySelector('.choice-wrap .choice-item[tabindex="0"]') as HTMLElement|null)?.focus()
// #endif
});if(seconds.value>0)timer=setInterval(()=>{if(props.paused)return;seconds.value--;if(seconds.value<=0){clearInterval(timer);const c=props.choices.find(c=>c.defaultChoice&&!c.disabled)||props.choices.find(c=>!c.disabled);if(c)pick(c)}},1000)});onUnmounted(()=>{clearInterval(timer);clearTimeout(commit)})
</script><style scoped>
.choice-wrap{position:absolute;inset:0;z-index:var(--z-choice);display:flex;align-items:center;justify-content:flex-end;padding:80px var(--ui-safe-x) 88px;background:linear-gradient(90deg,#0000 40%,#08090b26 65%,#08090bb3)}.choice-box{width:clamp(320px,30vw,430px);position:relative}.head{display:flex;flex-direction:column-reverse;align-items:center;gap:14px;margin-bottom:24px}.title{font-family:'Songti SC','STSong',serif;font-size:clamp(15px,1.2vw,20px);letter-spacing:.14em;color:#e6d9c2}.timer{width:64px;height:64px;position:relative}.timer text{position:absolute;inset:0;display:flex;align-items:center;justify-content:center;font:32px/1 serif}.options{display:flex;flex-direction:column;gap:18px}.major{justify-content:center;background:radial-gradient(ellipse at center,#0000 10%,#08090b88 90%)}.major-portrait{position:absolute;width:28%;height:65%;left:36%;top:25%;mask-image:radial-gradient(ellipse at 50% 42%,#000 25%,#0008 52%,transparent 72%);opacity:.82}.major-crack{position:absolute;inset:0;opacity:.17;mix-blend-mode:screen}.major .choice-box{width:100%}.major .head{margin-bottom:7vh}.major .title{font-size:clamp(22px,2.3vw,36px);letter-spacing:.3em}.major .options{display:grid;grid-template-columns:1fr 1fr;column-gap:29vw;row-gap:40px;padding:0 3vw}.major .options .choice-item:nth-child(1),.major .options .choice-item:nth-child(2){clip-path:polygon(2% 25%,94% 0,100% 92%,0 85%)}.major .options .choice-item:nth-child(3),.major .options .choice-item:nth-child(4){clip-path:polygon(0 8%,96% 18%,100% 90%,4% 100%)}.major .options .choice-item:nth-child(5),.major .options .choice-item:nth-child(6){clip-path:polygon(0 0,100% 20%,95% 100%,4% 90%)}.major .choice-item:nth-child(odd){transform:rotate(-4deg)}.major .choice-item:nth-child(even){transform:rotate(4deg)}.major .branch-dim{opacity:.45}.major-note{display:block;text-align:center;margin-top:5vh;color:#d2c1a2;font:14px serif;letter-spacing:.2em}
@media(max-height:540px) and (orientation:landscape){.choice-wrap{padding:48px 4vw 48px}.choice-box{width:clamp(260px,34vw,380px)}.head{flex-direction:row;justify-content:space-between;gap:8px;margin-bottom:12px}.timer{height:40px;width:40px}.timer text{font-size:23px}.options{gap:13px}.major .options{column-gap:23vw;row-gap:16px}.major .head{margin-bottom:20px}.major-note{margin-top:18px;font-size:11px}}
</style>