<template><button role="button" :tabindex="item.disabled||busy?-1:0" :aria-disabled="!!(item.disabled||busy)" @keydown.enter.prevent="activateFocused" @keydown.space.prevent="activateFocused" class="choice-item" :class="{selected,hovered,locked:item.locked,major}" :disabled="item.disabled||busy" :aria-label="item.locked?'尚未明晰的命运':item.text" @mouseenter="hovered=true" @mouseleave="hovered=false" @focus="hovered=true" @blur="hovered=false" @click="$emit('pick',item)">
<ScenicFrame kind="dialogue" surface/><view class="choice-art" :style="{borderImageSource:`url(${baseSkin})`}"/><view class="choice-highlight" :style="{borderImageSource:`url(${stateSkin})`}"/>
<view v-if="major" class="mirror-crack" :style="{backgroundImage:`url(${uiAssets.decorations.crack})`}"/>
<text v-if="developerMode&&!item.locked" class="choice-id">{{item.id}}</text><text class="choice-copy" :aria-hidden="item.locked">{{item.locked?'···':item.text}}</text>
</button></template><script setup lang="ts">
import ScenicFrame from '../common/ScenicFrame.vue'
import {activateFocused} from '../../utils/keyboard';

import {computed,ref} from 'vue';import {uiAssets} from '../../config/ui-assets';import type {ChoiceItem} from '../../data/story';const props=defineProps<{item:ChoiceItem;selected?:boolean;busy?:boolean;developerMode?:boolean;major?:boolean}>();defineEmits<{pick:[ChoiceItem]}>();const hovered=ref(false);const baseSkin=computed(()=>props.item.disabled?uiAssets.choice.disabled:uiAssets.choice.normal);const stateSkin=computed(()=>props.selected?uiAssets.choice.selected:uiAssets.choice.hover)
</script><style scoped>
.choice-item{--choice-art-safe-left:var(--choice-safe-left);position:relative;isolation:isolate;width:100%;min-height:76px;margin:0;padding:19px var(--choice-safe-right) 19px var(--choice-art-safe-left);background:transparent;border:0;border-radius:0;overflow:visible;color:var(--text);font-size:clamp(15px,1.15vw,22px);text-align:left;line-height:1.55;cursor:pointer;transition:filter .25s,transform .25s;animation:choice-enter .45s both}.choice-item:after{border:0}.choice-art,.choice-highlight{position:absolute;inset:0;z-index:-1;border-style:solid;border-color:transparent;border-width:12px 24px 12px 76px;border-image-slice:18 38 18 120 fill;border-image-width:12px 24px 12px 76px;pointer-events:none}.choice-art{opacity:.7}.choice-highlight{opacity:0;transition:opacity .25s;mix-blend-mode:screen}.hovered .choice-highlight{opacity:.15}.selected{transform:scale(.985);color:#fff5da;filter:drop-shadow(0 0 4px #c9a35d66)}.selected .choice-highlight{opacity:.2}.choice-copy{display:block;position:relative;overflow-wrap:anywhere}.choice-id{position:absolute;right:var(--choice-safe-right);top:-8px;font:9px/1 ui-monospace,monospace;letter-spacing:.08em;color:#bca47a;background:#0a0b0de6;padding:3px 6px}.choice-item[disabled]{cursor:default;opacity:.36;background:transparent!important;color:var(--text)!important}.choice-item.locked{filter:blur(2px);opacity:.22}.choice-item.locked .choice-copy{letter-spacing:1em}.mirror-crack{position:absolute;inset:0;z-index:-1;background-size:cover;opacity:.15;mix-blend-mode:screen}.major{min-height:90px;background:linear-gradient(110deg,#06060888,#08090b33);border-top:1px solid #c5a56e55;clip-path:polygon(0 12%,96% 0,100% 86%,3% 100%)}.major .choice-art{opacity:.23}.major .choice-highlight{opacity:0}.major.hovered .choice-highlight{opacity:.2}
@media(max-height:540px) and (orientation:landscape){.choice-item{min-height:52px;padding-top:12px;padding-bottom:12px;font-size:15px}.choice-art,.choice-highlight{border-left-width:64px;border-image-width:10px 22px 10px 64px}.major{min-height:62px}}
.major .choice-id{top:20px;font-size:8px;background:none} </style>